import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import theme from "@/theme";
import { ThemeProvider } from "@mui/material/styles";
import { NavigationMenu } from "./components/navigation/NavigationMenu";
import { navigationActions } from "./components/navigation/navigationActions";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <NavigationMenu
              isAuthorized={!!session}
              navigationActions={navigationActions}
            >
              {children}
            </NavigationMenu>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
